#define ONESHOT_TAP_TOGGLE 1

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 500

#define USB_SUSPEND_WAKEUP_DELAY 0
#define FIRMWARE_VERSION u8"rzxQ7/Xjzx9"
#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61
#define LAYER_STATE_8BIT

#define TAPPING_TERM 190

#include "rgb-reset.h"

#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_DEFAULT_SPD 80

#define COMBO_TERM 15
